usr/lib/ipsec/
/var/lib/vyatta-security-vpn
/opt/vyatta/bin
/opt/vyatta/etc
/opt/vyatta/sbin
opt/vyatta/share
etc/logrotate.d/
etc/systemd/system/strongswan.service.d/
python/vyatta/vpn/ipsec/*.py usr/lib/python3/dist-packages/vyatta/vpn/ipsec
tmpfiles.d/vyatta-ipsec.conf usr/lib/tmpfiles.d
tmplscripts/security/vpn/configd_end.sh	opt/vyatta/share/tmplscripts/security/vpn/
tmplscripts/security/vpn/ipsec/site-to-site/configd_begin.pl	opt/vyatta/share/tmplscripts/security/vpn/ipsec/site-to-site/
